export type SkinType = "oily" | "dry" | "combination" | "sensitive" | "normal"
export type ProductCategory = "skincare" | "makeup" | "haircare" | "fragrance" | "bodycare"
export type SkinConcern = "acne" | "darkspots" | "aging" | "dryness" | "sensitivity" | "oiliness"

export interface Ingredient {
  name: string
  nameVi: string
  benefit: string
  avoid?: boolean
}

export interface Review {
  id: string
  userName: string
  rating: number
  comment: string
  verified: boolean
  date: string
  images?: string[]
  skinType?: SkinType
}

export interface Product {
  id: string
  name: string
  brand: string
  category: ProductCategory
  price: number
  originalPrice?: number
  image: string
  images: string[]
  description: string
  volume: string
  suitableFor: SkinType[]
  concerns: SkinConcern[]
  ingredients: Ingredient[]
  rating: number
  reviewCount: number
  reviews: Review[]
  trending: boolean
  new: boolean
}

// Sample data - would come from database in production
export const sampleProducts: Product[] = [
  {
    id: "1",
    name: "Serum Vitamin C",
    brand: "SkinGlow",
    category: "skincare",
    price: 580000,
    originalPrice: 650000,
    image: "/vitamin-c-serum-bottle-minimal.jpg",
    images: ["/vitamin-c-serum-bottle.jpg", "/serum-texture-closeup.jpg", "/serum-bottle-360-view.jpg"],
    description: "Serum Vitamin C 15% giúp làm sáng da, mờ thâm nám và bảo vệ da khỏi tác hại của môi trường.",
    volume: "30ml",
    suitableFor: ["normal", "combination", "oily"],
    concerns: ["darkspots", "aging", "dryness"],
    ingredients: [
      { name: "Vitamin C", nameVi: "Vitamin C", benefit: "Làm sáng da, chống oxy hóa" },
      { name: "Hyaluronic Acid", nameVi: "Axit Hyaluronic", benefit: "Cấp ẩm sâu, làm căng mịn da" },
      { name: "Ferulic Acid", nameVi: "Axit Ferulic", benefit: "Tăng cường hiệu quả Vitamin C" },
      { name: "Glycerin", nameVi: "Glycerin", benefit: "Dưỡng ẩm, giữ nước cho da" },
    ],
    rating: 4.7,
    reviewCount: 234,
    reviews: [
      {
        id: "r1",
        userName: "Nguyễn Minh A",
        rating: 5,
        comment: "Sản phẩm rất tốt, da sáng lên sau 2 tuần sử dụng. Không bị kích ứng gì cả!",
        verified: true,
        date: "2024-11-15",
        skinType: "combination",
        images: ["/before-after-skin.jpg"],
      },
      {
        id: "r2",
        userName: "Trần Thu H",
        rating: 4,
        comment: "Texture nhẹ, thấm nhanh. Thấy da đều màu hơn.",
        verified: true,
        date: "2024-11-10",
        skinType: "oily",
      },
    ],
    trending: true,
    new: false,
  },
  {
    id: "2",
    name: "Kem dưỡng ẩm Ceramide",
    brand: "HydraLux",
    category: "skincare",
    price: 520000,
    image: "/moisturizer-cream-jar.jpg",
    images: ["/moisturizer-cream-jar.jpg", "/cream-texture.jpg"],
    description: "Kem dưỡng ẩm chứa 5 loại Ceramide giúp phục hồi hàng rào bảo vệ da, dưỡng ẩm sâu 24h.",
    volume: "50ml",
    suitableFor: ["dry", "sensitive", "normal"],
    concerns: ["dryness", "sensitivity"],
    ingredients: [
      { name: "Ceramide Complex", nameVi: "Phức hợp Ceramide", benefit: "Phục hồi hàng rào bảo vệ da" },
      { name: "Niacinamide", nameVi: "Niacinamide", benefit: "Sáng da, se khít lỗ chân lông" },
      { name: "Centella Asiatica", nameVi: "Rau má", benefit: "Làm dịu, kháng viêm" },
    ],
    rating: 4.8,
    reviewCount: 189,
    reviews: [],
    trending: false,
    new: true,
  },
  {
    id: "3",
    name: "Retinol Night Serum 0.5%",
    brand: "SkinGlow",
    category: "skincare",
    price: 680000,
    image: "/retinol-serum-purple-bottle.jpg",
    images: ["/retinol-serum-purple-bottle.jpg"],
    description: "Serum Retinol 0.5% giúp giảm nếp nhăn, làm mịn da và cải thiện kết cấu da ban đêm.",
    volume: "30ml",
    suitableFor: ["normal", "combination", "oily"],
    concerns: ["aging", "acne"],
    ingredients: [
      { name: "Retinol", nameVi: "Retinol", benefit: "Chống lão hóa, tái tạo da" },
      { name: "Squalane", nameVi: "Squalane", benefit: "Dưỡng ẩm, làm mềm da" },
      { name: "Vitamin E", nameVi: "Vitamin E", benefit: "Chống oxy hóa, bảo vệ da" },
    ],
    rating: 4.6,
    reviewCount: 156,
    reviews: [],
    trending: true,
    new: false,
  },
  {
    id: "4",
    name: "Kem chống nắng SPF 50+",
    brand: "SunShield",
    category: "skincare",
    price: 320000,
    image: "/sunscreen-tube-beach.jpg",
    images: ["/sunscreen-tube-beach.jpg"],
    description: "Kem chống nắng dạng gel nhẹ, không gây nhờn, bảo vệ da toàn diện khỏi tia UV.",
    volume: "50ml",
    suitableFor: ["oily", "combination", "normal"],
    concerns: ["aging", "darkspots"],
    ingredients: [
      { name: "Zinc Oxide", nameVi: "Kẽm Oxide", benefit: "Chống nắng vật lý" },
      { name: "Niacinamide", nameVi: "Niacinamide", benefit: "Sáng da, se khít lỗ chân lông" },
    ],
    rating: 4.5,
    reviewCount: 312,
    reviews: [],
    trending: true,
    new: false,
  },
  {
    id: "5",
    name: "Son kem lì Velvet Matte",
    brand: "LipLuxe",
    category: "makeup",
    price: 280000,
    image: "/matte-liquid-lipstick-red.jpg",
    images: ["/matte-liquid-lipstick-red.jpg"],
    description: "Son kem lì mịn môi, bền màu 12h, không gây khô môi với công thức chứa Vitamin E.",
    volume: "4.5ml",
    suitableFor: ["normal", "dry", "combination", "oily", "sensitive"],
    concerns: [],
    ingredients: [
      { name: "Vitamin E", nameVi: "Vitamin E", benefit: "Dưỡng ẩm môi" },
      { name: "Jojoba Oil", nameVi: "Dầu Jojoba", benefit: "Làm mềm môi" },
    ],
    rating: 4.4,
    reviewCount: 428,
    reviews: [],
    trending: true,
    new: true,
  },
  {
    id: "6",
    name: "Sữa rửa mặt BHA 2%",
    brand: "ClearSkin",
    category: "skincare",
    price: 380000,
    image: "/bha-cleanser-bottle.jpg",
    images: ["/bha-cleanser-bottle.jpg"],
    description: "Sữa rửa mặt BHA 2% giúp làm sạch sâu lỗ chân lông, kiểm soát dầu và ngăn ngừa mụn.",
    volume: "150ml",
    suitableFor: ["oily", "combination"],
    concerns: ["acne", "oiliness"],
    ingredients: [
      { name: "BHA (Salicylic Acid)", nameVi: "BHA (Axit Salicylic)", benefit: "Làm sạch lỗ chân lông, trị mụn" },
      { name: "Tea Tree Oil", nameVi: "Tinh dầu tràm trà", benefit: "Kháng khuẩn, giảm viêm" },
      { name: "Alcohol", nameVi: "Cồn", benefit: "Làm sạch", avoid: true },
    ],
    rating: 4.3,
    reviewCount: 267,
    reviews: [],
    trending: false,
    new: false,
  },
  {
    id: "7",
    name: "Cushion che phủ Perfect",
    brand: "PerfectFace",
    category: "makeup",
    price: 420000,
    image: "/cushion-compact-beige.jpg",
    images: ["/cushion-compact-beige.jpg"],
    description: "Cushion che phủ tốt, lâu trôi, cho lớp nền mịn mượt tự nhiên suốt cả ngày.",
    volume: "15g",
    suitableFor: ["normal", "dry", "combination", "oily", "sensitive"],
    concerns: ["darkspots"],
    ingredients: [
      { name: "SPF 50+ PA+++", nameVi: "SPF 50+ PA+++", benefit: "Chống nắng" },
      { name: "Niacinamide", nameVi: "Niacinamide", benefit: "Sáng da" },
    ],
    rating: 4.6,
    reviewCount: 189,
    reviews: [],
    trending: false,
    new: true,
  },
  {
    id: "8",
    name: "Mascara dưỡng mi",
    brand: "LashPro",
    category: "makeup",
    price: 340000,
    image: "/mascara-black-tube.jpg",
    images: ["/mascara-black-tube.jpg"],
    description: "Mascara không trôi, không lem, giúp mi dài cong vút cả ngày với chiết xuất dưỡng mi.",
    volume: "8ml",
    suitableFor: ["normal", "dry", "combination", "oily", "sensitive"],
    concerns: [],
    ingredients: [
      { name: "Vitamin E", nameVi: "Vitamin E", benefit: "Dưỡng mi" },
      { name: "Peptides", nameVi: "Peptides", benefit: "Kích thích mọc mi" },
    ],
    rating: 4.5,
    reviewCount: 276,
    reviews: [],
    trending: true,
    new: false,
  },
  {
    id: "9",
    name: "Dầu dưỡng tóc Argan",
    brand: "HairSilk",
    category: "haircare",
    price: 380000,
    image: "/hair-oil-bottle.jpg",
    images: ["/hair-oil-bottle.jpg"],
    description: "Dầu dưỡng tóc Argan nguyên chất giúp tóc mềm mượt, bóng khỏe và phục hồi hư tổn.",
    volume: "50ml",
    suitableFor: ["normal", "dry", "combination", "oily", "sensitive"],
    concerns: [],
    ingredients: [
      { name: "Argan Oil", nameVi: "Dầu Argan", benefit: "Dưỡng ẩm, phục hồi tóc" },
      { name: "Vitamin E", nameVi: "Vitamin E", benefit: "Chống oxy hóa" },
    ],
    rating: 4.7,
    reviewCount: 145,
    reviews: [],
    trending: true,
    new: false,
  },
  {
    id: "10",
    name: "Nước hoa nam Flora Musk",
    brand: "Essence",
    category: "fragrance",
    price: 1200000,
    image: "/perfume-bottle-mens.jpg",
    images: ["/perfume-bottle-mens.jpg"],
    description: "Nước hoa nam hương gỗ xạ hương sang trọng, lưu hương lâu, phù hợp mọi dịp.",
    volume: "50ml",
    suitableFor: ["normal", "dry", "combination", "oily", "sensitive"],
    concerns: [],
    ingredients: [],
    rating: 4.8,
    reviewCount: 89,
    reviews: [],
    trending: true,
    new: true,
  },
  {
    id: "11",
    name: "Toner cân bằng da AHA/BHA",
    brand: "GlowEssence",
    category: "skincare",
    price: 350000,
    image: "/toner-bottle-minimalist.jpg",
    images: ["/toner-bottle-minimalist.jpg"],
    description: "Toner loại bỏ tế bào chết, cân bằng pH da, giúp da sáng mịn và đều màu.",
    volume: "200ml",
    suitableFor: ["oily", "combination", "normal"],
    concerns: ["acne", "darkspots"],
    ingredients: [
      { name: "AHA", nameVi: "AHA", benefit: "Tẩy tế bào chết bề mặt" },
      { name: "BHA", nameVi: "BHA", benefit: "Làm sạch lỗ chân lông" },
      { name: "Witch Hazel", nameVi: "Cây phỉ", benefit: "Se khít lỗ chân lông" },
    ],
    rating: 4.5,
    reviewCount: 198,
    reviews: [],
    trending: true,
    new: false,
  },
  {
    id: "12",
    name: "Kem mắt chống lão hóa",
    brand: "LuxeCare",
    category: "skincare",
    price: 580000,
    image: "/eye-cream-luxury.jpg",
    images: ["/eye-cream-luxury.jpg"],
    description: "Kem mắt giảm quầng thâm, nếp nhăn và bọng mắt với công nghệ peptide tiên tiến.",
    volume: "15ml",
    suitableFor: ["dry", "normal", "combination", "sensitive"],
    concerns: ["aging", "darkspots"],
    ingredients: [
      { name: "Caffeine", nameVi: "Caffeine", benefit: "Giảm bọng mắt" },
      { name: "Peptides", nameVi: "Peptides", benefit: "Chống lão hóa" },
      { name: "Vitamin K", nameVi: "Vitamin K", benefit: "Giảm quầng thâm" },
    ],
    rating: 4.6,
    reviewCount: 167,
    reviews: [],
    trending: false,
    new: true,
  },
  {
    id: "13",
    name: "Mặt nạ đất sét thanh lọc",
    brand: "PureNature",
    category: "skincare",
    price: 290000,
    image: "/clay-mask-jar.jpg",
    images: ["/clay-mask-jar.jpg"],
    description: "Mặt nạ đất sét hút dầu, làm sạch sâu lỗ chân lông, giúp da sạch mịn.",
    volume: "100g",
    suitableFor: ["oily", "combination"],
    concerns: ["acne", "oiliness"],
    ingredients: [
      { name: "Kaolin Clay", nameVi: "Đất sét Kaolin", benefit: "Hút dầu, làm sạch" },
      { name: "Charcoal", nameVi: "Than hoạt tính", benefit: "Hút độc tố" },
      { name: "Tea Tree", nameVi: "Tràm trà", benefit: "Kháng khuẩn" },
    ],
    rating: 4.4,
    reviewCount: 223,
    reviews: [],
    trending: false,
    new: false,
  },
  {
    id: "14",
    name: "Xịt khoáng dưỡng da",
    brand: "AquaGlow",
    category: "skincare",
    price: 250000,
    image: "/facial-mist-spray.jpg",
    images: ["/facial-mist-spray.jpg"],
    description: "Xịt khoáng cấp ẩm tức thì, làm dịu da, giúp lớp trang điểm bền màu hơn.",
    volume: "150ml",
    suitableFor: ["normal", "dry", "sensitive", "combination", "oily"],
    concerns: ["dryness", "sensitivity"],
    ingredients: [
      { name: "Thermal Water", nameVi: "Nước khoáng", benefit: "Cấp ẩm, làm dịu" },
      { name: "Aloe Vera", nameVi: "Nha đam", benefit: "Làm dịu, dưỡng ẩm" },
    ],
    rating: 4.3,
    reviewCount: 134,
    reviews: [],
    trending: false,
    new: false,
  },
  {
    id: "15",
    name: "BB Cream che khuyết điểm",
    brand: "BeautyBase",
    category: "makeup",
    price: 310000,
    image: "/bb-cream-tube.jpg",
    images: ["/bb-cream-tube.jpg"],
    description: "BB cream che khuyết điểm tốt, dưỡng da, chống nắng SPF 30.",
    volume: "40ml",
    suitableFor: ["normal", "dry", "combination"],
    concerns: ["darkspots"],
    ingredients: [
      { name: "SPF 30", nameVi: "SPF 30", benefit: "Chống nắng" },
      { name: "Hyaluronic Acid", nameVi: "Axit Hyaluronic", benefit: "Cấp ẩm" },
    ],
    rating: 4.4,
    reviewCount: 201,
    reviews: [],
    trending: true,
    new: false,
  },
  {
    id: "16",
    name: "Phấn mắt màu Nude",
    brand: "ColorStudio",
    category: "makeup",
    price: 450000,
    image: "/eyeshadow-palette-nude.jpg",
    images: ["/eyeshadow-palette-nude.jpg"],
    description: "Bảng phấn mắt 12 ô màu nude đa năng, dễ tán, bám màu lâu cả ngày.",
    volume: "12 x 1.5g",
    suitableFor: ["normal", "dry", "combination", "oily", "sensitive"],
    concerns: [],
    ingredients: [
      { name: "Mica", nameVi: "Mica", benefit: "Tạo độ lấp lánh" },
      { name: "Vitamin E", nameVi: "Vitamin E", benefit: "Dưỡng da mí" },
    ],
    rating: 4.7,
    reviewCount: 312,
    reviews: [],
    trending: true,
    new: false,
  },
  {
    id: "17",
    name: "Sữa dưỡng thể dưỡng ẩm",
    brand: "BodyBliss",
    category: "bodycare",
    price: 280000,
    image: "/body-lotion-pump.jpg",
    images: ["/body-lotion-pump.jpg"],
    description: "Sữa dưỡng thể dưỡng ẩm sâu, thấm nhanh, không gây nhờn rít.",
    volume: "250ml",
    suitableFor: ["normal", "dry", "combination", "oily", "sensitive"],
    concerns: ["dryness"],
    ingredients: [
      { name: "Shea Butter", nameVi: "Bơ hạt mỡ", benefit: "Dưỡng ẩm sâu" },
      { name: "Coconut Oil", nameVi: "Dầu dừa", benefit: "Làm mềm da" },
    ],
    rating: 4.6,
    reviewCount: 178,
    reviews: [],
    trending: false,
    new: true,
  },
  {
    id: "18",
    name: "Dầu gội phục hồi tóc hư tổn",
    brand: "HairRevive",
    category: "haircare",
    price: 320000,
    image: "/shampoo-repair-bottle.jpg",
    images: ["/shampoo-repair-bottle.jpg"],
    description: "Dầu gội phục hồi tóc hư tổn, giúp tóc mềm mượt và khỏe mạnh từ gốc đến ngọn.",
    volume: "300ml",
    suitableFor: ["normal", "dry", "combination", "oily", "sensitive"],
    concerns: [],
    ingredients: [
      { name: "Keratin", nameVi: "Keratin", benefit: "Phục hồi tóc" },
      { name: "Argan Oil", nameVi: "Dầu Argan", benefit: "Dưỡng ẩm tóc" },
    ],
    rating: 4.5,
    reviewCount: 267,
    reviews: [],
    trending: false,
    new: false,
  },
  {
    id: "19",
    name: "Nước hoa nữ Floral Dream",
    brand: "PerfumeLux",
    category: "fragrance",
    price: 980000,
    image: "/perfume-floral-bottle.jpg",
    images: ["/perfume-floral-bottle.jpg"],
    description: "Nước hoa nữ hương hoa cỏ ngọt ngào, nhẹ nhàng, thích hợp cho ngày hè.",
    volume: "50ml",
    suitableFor: ["normal", "dry", "combination", "oily", "sensitive"],
    concerns: [],
    ingredients: [],
    rating: 4.8,
    reviewCount: 156,
    reviews: [],
    trending: true,
    new: true,
  },
  {
    id: "20",
    name: "Gel rửa mặt làm sạch sâu",
    brand: "FreshFace",
    category: "skincare",
    price: 290000,
    image: "/gel-cleanser-tube.jpg",
    images: ["/gel-cleanser-tube.jpg"],
    description: "Gel rửa mặt làm sạch sâu, không làm khô da, phù hợp mọi loại da.",
    volume: "150ml",
    suitableFor: ["normal", "combination", "oily"],
    concerns: ["acne", "oiliness"],
    ingredients: [
      { name: "Salicylic Acid", nameVi: "Axit Salicylic", benefit: "Làm sạch lỗ chân lông" },
      { name: "Green Tea", nameVi: "Trà xanh", benefit: "Chống oxy hóa" },
    ],
    rating: 4.4,
    reviewCount: 289,
    reviews: [],
    trending: false,
    new: false,
  },
  {
    id: "21",
    name: "Phấn phủ kiềm dầu",
    brand: "MatteMagic",
    category: "makeup",
    price: 380000,
    image: "/powder-compact-translucent.jpg",
    images: ["/powder-compact-translucent.jpg"],
    description: "Phấn phủ kiềm dầu hiệu quả, giúp lớp nền lâu trôi và mịn màng.",
    volume: "15g",
    suitableFor: ["oily", "combination"],
    concerns: ["oiliness"],
    ingredients: [
      { name: "Silica", nameVi: "Silica", benefit: "Hấp thụ dầu" },
      { name: "Vitamin E", nameVi: "Vitamin E", benefit: "Dưỡng da" },
    ],
    rating: 4.5,
    reviewCount: 234,
    reviews: [],
    trending: true,
    new: false,
  },
  {
    id: "22",
    name: "Dầu xả mượt tóc",
    brand: "SilkTouch",
    category: "haircare",
    price: 340000,
    image: "/conditioner-smooth-bottle.jpg",
    images: ["/conditioner-smooth-bottle.jpg"],
    description: "Dầu xả giúp tóc mượt mà, dễ chải và giảm gãy rụng.",
    volume: "300ml",
    suitableFor: ["normal", "dry", "combination", "oily", "sensitive"],
    concerns: [],
    ingredients: [
      { name: "Silk Protein", nameVi: "Protein tơ tằm", benefit: "Làm mượt tóc" },
      { name: "Jojoba Oil", nameVi: "Dầu Jojoba", benefit: "Dưỡng ẩm" },
    ],
    rating: 4.6,
    reviewCount: 198,
    reviews: [],
    trending: false,
    new: true,
  },
  {
    id: "23",
    name: "Chì kẻ mày chống nước",
    brand: "BrowPro",
    category: "makeup",
    price: 220000,
    image: "/eyebrow-pencil-waterproof.jpg",
    images: ["/eyebrow-pencil-waterproof.jpg"],
    description: "Chì kẻ mày chống nước, giữ màu lâu, dễ tạo hình lông mày tự nhiên.",
    volume: "0.3g",
    suitableFor: ["normal", "dry", "combination", "oily", "sensitive"],
    concerns: [],
    ingredients: [{ name: "Vitamin E", nameVi: "Vitamin E", benefit: "Dưỡng lông mày" }],
    rating: 4.3,
    reviewCount: 145,
    reviews: [],
    trending: false,
    new: false,
  },
  {
    id: "24",
    name: "Tinh chất phục hồi da AHA",
    brand: "GlowEssence",
    category: "skincare",
    price: 520000,
    image: "/aha-essence-bottle.jpg",
    images: ["/aha-essence-bottle.jpg"],
    description: "Tinh chất AHA giúp tẩy tế bào chết nhẹ nhàng, làm sáng và đều màu da.",
    volume: "30ml",
    suitableFor: ["normal", "combination", "oily"],
    concerns: ["darkspots", "aging"],
    ingredients: [
      { name: "Glycolic Acid", nameVi: "Axit Glycolic", benefit: "Tẩy tế bào chết" },
      { name: "Lactic Acid", nameVi: "Axit Lactic", benefit: "Làm sáng da" },
      { name: "Aloe Vera", nameVi: "Nha đam", benefit: "Làm dịu" },
    ],
    rating: 4.7,
    reviewCount: 223,
    reviews: [],
    trending: true,
    new: true,
  },
]

export function getProductById(id: string): Product | undefined {
  return sampleProducts.find((p) => p.id === id)
}

export function getProductsByCategory(category: ProductCategory): Product[] {
  return sampleProducts.filter((p) => p.category === category)
}

export function getTrendingProducts(): Product[] {
  return sampleProducts.filter((p) => p.trending)
}

export function getNewProducts(): Product[] {
  return sampleProducts.filter((p) => p.new)
}

export function getFeaturedProducts(): Product[] {
  // Return products sorted by review count (most popular)
  return [...sampleProducts].sort((a, b) => b.reviewCount - a.reviewCount)
}
